import { networkInterfaces } from 'node:os';
import { randomBytes } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import QRCode from 'qrcode';
import { createMobileBridge } from '../server/mobile-bridge';
const address=Object.values(networkInterfaces()).flat().find(i=>i?.family==='IPv4' && !i.internal && /^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(i.address))?.address;
if(!address) throw new Error('Connect this Mac and the iPhone to the same private Wi-Fi/hotspot.');
const key=randomBytes(32), expiresAt=Date.now()+60*60_000;
const pairing={version:1,url:`http://${address}:8790/paired`,key:key.toString('hex'),expiresAt};
await mkdir('artifacts',{recursive:true});
const data=JSON.stringify(pairing), qr=await QRCode.toDataURL(data,{width:400,margin:2});
await writeFile('artifacts/mobile-pairing.json',data,{mode:0o600});
const expoURL=`exp://${address}:8082`, appQR=await QRCode.toDataURL(expoURL,{width:400,margin:2});
await writeFile('artifacts/iphone-open.html',`<!doctype html><meta name="viewport" content="width=device-width"><title>Step 1 — Open app</title><style>body{font:20px system-ui;max-width:620px;margin:30px auto;padding:20px}img{max-width:100%}a{color:#176542}</style><h1>Step 1 — Open app</h1><p>Scan this QR using the <strong>iPhone Camera</strong>. Tap the banner to open <strong>Expo Go</strong>.</p><img src="${appQR}" alt="Public Expo Go app-opening QR"><p><a href="${expoURL}">${expoURL}</a></p><p>Keep your Mac awake and your phone on the same Wi-Fi. If Expo Go requests sign-in, use the same free Expo account as this Mac (karawalla).</p><p>Once the app opens: <strong>Settings → Pair Mac for local AI → Scan Mac pairing QR</strong>.</p><p>Then scan the <a href="mobile-pairing.html">Step 2 private QR</a> using the scanner <strong>inside the app</strong>.</p>`);
await writeFile('artifacts/mobile-pairing.html',`<!doctype html><meta name="viewport" content="width=device-width"><title>Step 2 — Private pairing</title><style>body{font:20px system-ui;max-width:600px;margin:40px auto;padding:20px}img{max-width:100%}textarea{width:100%;height:100px}.note{padding:16px;background:#fff1d6;border-radius:12px}</style><h1>Step 2 — Private pairing</h1><p class="note"><strong>Scan inside Document Review only.</strong> First <a href="iphone-open.html">open the app using the Step 1 QR</a>. This QR does not launch Expo Go.</p><p>In the app: <strong>Settings → Pair Mac for local AI → Scan Mac pairing QR</strong>.</p><img src="${qr}" alt="Private pairing QR — scan inside Document Review"><p>Keep this screen private. Code expires in one hour. Same Wi-Fi; Mac awake. Ollama remains on the Mac. Only encrypted minimized facts cross this connection.</p><details><summary>Manual pairing / simulator</summary><textarea readonly>${data}</textarea></details>`,{mode:0o600});
createMobileBridge(key,`${address}:8790`,fetch,expiresAt).listen(8790,address,()=>console.log(`Paired companion ready on ${address}:8790. Open artifacts/mobile-pairing.html locally. No key is logged. Stop/restart to revoke pairing.`));
