// Controlled browser health-unavailable rehearsal; real comparison rules, no AI.
// Does NOT stop Ollama or represent a real model-service outage.
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
const cli = (...args) => execFileSync('npx', ['--yes', 'agent-browser', ...args], { encoding: 'utf8', timeout: 90000 }).trim();
const evaluate = code => JSON.parse(cli('eval', code));
const click = name => cli('find', 'role', 'button', 'click', '--name', name);
mkdirSync('artifacts', { recursive: true });
cli('open', 'http://127.0.0.1:8787');
cli('snapshot', '-i');
click('Reset case');
cli('select', '#scenario', 'address-conflict');
click('Load demo pair');
cli('wait', '--fn', 'document.querySelectorAll(".document-card.loaded").length === 2 && !document.querySelector(".status-message")');
cli('wait', '--fn', '!!document.querySelector(".model-status .text-button")');
try {
  evaluate(`(() => {
    window.__phase5OriginalFetch = window.fetch;
    window.__phase5GenerationAttempts = 0;
    window.fetch = function(input, options) {
      const url = typeof input === 'string' ? input : input.url;
      if (url.includes('/api/send')) window.__phase5GenerationAttempts++;
      if (url.includes('/api/health')) return Promise.resolve(new Response(JSON.stringify({
        available: false, model: 'qwen2.5:1.5b',
        destination: 'http://127.0.0.1:11434/api/generate',
        message: 'Controlled health-unavailable test; no actual Ollama outage.'
      }), { status: 200, headers: { 'Content-Type': 'application/json' } }));
      return window.__phase5OriginalFetch.call(window, input, options);
    };
    return true;
  })()`);
  cli('click', '.model-status .text-button');
  cli('wait', '--fn', '!!document.querySelector(".backup-button")');
  click('Show rule-based summary (AI unavailable)');
  assert.equal(evaluate(`(() => {
    const text = document.querySelector('.summary-result')?.textContent ?? '';
    return text.includes('Rule-based summary — AI unavailable') &&
      text.includes('Generated by comparison rules. No model response.') &&
      !text.includes('Real Ollama response') && window.__phase5GenerationAttempts === 0 &&
      document.querySelectorAll('.finding.conflicting').length === 1;
  })()`), true);
  cli('screenshot', '--full', 'artifacts/phase5-rule-backup.png');
  click('Reset case');
  assert.equal(evaluate('!document.querySelector(".summary-result") && document.querySelectorAll(".document-card.loaded").length === 0'), true);
  writeFileSync('artifacts/phase5-offline-report.json', JSON.stringify({
    mode: 'controlled browser health-unavailable response, not a real daemon outage',
    realPdfComparison: true, ruleSummaryClearlyLabeled: true,
    aiGenerationAttempts: 0, resetClearsResult: true
  }, null, 2));
  console.log('PASS controlled unavailable-health backup: real rules, explicit no-model label, zero generation attempts, clean reset.');
} finally {
  evaluate(`(() => { if (window.__phase5OriginalFetch) window.fetch = window.__phase5OriginalFetch; delete window.__phase5OriginalFetch; return true; })()`);
  cli('click', '.model-status .text-button');
}
