import React,{useState,useRef,useEffect} from 'react';
import {Alert,AppState,Modal,ScrollView,TextInput,View} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {CameraView,useCameraPermissions} from 'expo-camera';
import {useAppearance} from '../lib/appearance';
import {companion,readPairing} from '../lib/companion';
import {ActionButton,Copy,PageHeader,styles} from './UI';

export default function PairMac(){const {colors,pairing,setPairing}=useAppearance();const [open,setOpen]=useState(false),[code,setCode]=useState(''),[scan,setScan]=useState(false),[error,setError]=useState(''),[health,setHealth]=useState(''),[busy,setBusy]=useState(false);const [permission,requestPermission]=useCameraPermissions();const alive=useRef(true),revision=useRef(0),operation=useRef<AbortController|undefined>(undefined);
  useEffect(()=>{alive.current=true;const sub=AppState.addEventListener('change',state=>{if(state==='background'){revision.current++;operation.current?.abort();setOpen(false);setScan(false);setCode('');setBusy(false);setHealth('');}});return ()=>{alive.current=false;operation.current?.abort();sub.remove();};},[]);
  async function connect(value:string){const rev=++revision.current,controller=new AbortController();operation.current?.abort();operation.current=controller;setError('');setBusy(true);try{const p=readPairing(value);const h=await companion<{available:boolean;model:string;message:string}>(p,{action:'health'},controller.signal);if(!alive.current||rev!==revision.current)return;setPairing(p);setHealth(h.available?`${h.model} • ready on Mac`:h.message);setCode('');setScan(false);setOpen(false);}catch{if(alive.current&&rev===revision.current)setError('Could not connect. Keep the Mac awake on the same Wi-Fi and scan its current private QR.');}finally{if(alive.current&&rev===revision.current)setBusy(false);}}
  return <><View style={{gap:12}}><Copy bold size={19}>Local AI connection</Copy><Copy muted size={13}>{pairing?'Mac connected. Approved review facts go to local Qwen.':'Connect your Mac when you want an AI explanation. Reading and comparison work without it.'}</Copy><ActionButton title={pairing?'Pair a different Mac':'Pair Mac for local AI'} secondary icon="link" onPress={()=>{setError('');setOpen(true);}}/>{pairing&&<><Copy muted size={12}>{health||'Paired Mac. Check the connection before your demo.'}</Copy><ActionButton title="Check AI connection" secondary onPress={()=>{void companion<{available:boolean;model:string;message:string}>(pairing,{action:'health'}).then(h=>setHealth(h.available?`${h.model} • ready on Mac`:h.message)).catch(()=>setHealth('Paired Mac unreachable.'));}}/></>}</View><Modal visible={open} animationType="slide" onRequestClose={()=>{setOpen(false);setScan(false);setCode('');}}><SafeAreaProvider><SafeAreaView style={{flex:1,backgroundColor:colors.background}}><PageHeader title="Pair with your Mac" onBack={()=>{setOpen(false);setScan(false);setCode('');}}/><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><Copy>Keep your phone and Mac on the same Wi-Fi. Scan the private pairing QR shown on your Mac inside this app.</Copy><ActionButton title="Scan Mac pairing QR" icon="camera" onPress={()=>{void requestPermission().then(p=>p.granted?setScan(true):Alert.alert('Camera permission','Allow camera access or paste the pairing code.'));}}/>{scan&&permission?.granted&&<CameraView style={{height:300,borderRadius:16}} barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={({data})=>{setScan(false);void connect(data);}}/>}<Copy size={12} muted>Or paste the private pairing code from your Mac.</Copy><TextInput accessibilityLabel="Private pairing code" value={code} onChangeText={setCode} multiline autoCapitalize="none" autoCorrect={false} style={{minHeight:110,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:14,color:colors.text,backgroundColor:colors.surface,textAlignVertical:'top'}}/>{!!error&&<Copy>{error}</Copy>}<ActionButton title={busy?'Connecting…':'Connect Mac'} disabled={!code||busy} onPress={()=>void connect(code)}/><Copy size={12} muted>Only approved, minimized facts leave the phone. The Mac must remain awake. No cloud service is enabled.</Copy></ScrollView></SafeAreaView></SafeAreaProvider></Modal></>;
}
