import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,AppState,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {WebView} from 'react-native-webview';
import * as ImagePicker from 'expo-image-picker';
import {File,Paths} from 'expo-file-system';
import {z} from 'zod';
import {GLOSSARY,PHOTO_LIMITS,boxSchema,photoLineSchema,visibleLines,detectPhoto,photoFields,photoContext,termsIn,type PhotoLine} from '../../src/shared/photo';
import {validateSummary,type RequestPreview,type ReviewSummary} from '../../src/shared/request';
import type {Pairing} from '../../src/shared/mobile-protocol';
import {companion,verifyPreview} from '../lib/companion';
import {useAppearance,type Palette} from '../lib/appearance';

type Result={lines:PhotoLine[];masks:z.infer<typeof boxSchema>[];latencyMs:number;width:number;height:number};
const resultSchema=z.strictObject({type:z.literal('result'),lines:z.array(photoLineSchema).max(PHOTO_LIMITS.lines),masks:z.array(boxSchema).max(PHOTO_LIMITS.masks),latencyMs:z.number().nonnegative(),width:z.number().int().positive().max(PHOTO_LIMITS.side),height:z.number().int().positive().max(PHOTO_LIMITS.side)});
function Action({title,onPress,disabled=false,secondary=false,testID}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean;testID?:string}){const {colors}=useAppearance(),s=makeStyles(colors);return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} testID={testID} style={[s.button,secondary&&s.secondary,disabled&&s.disabled]}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{title}</Text></Pressable>;}
export default function PhotoLens({pairing,onClose}:{pairing?:Pairing;onClose:()=>void}){
  const {colors,dark}=useAppearance(),s=makeStyles(colors);
  const [photoStep,setPhotoStep]=useState(0),[canvasOpen,setCanvasOpen]=useState(false),[fieldsOpen,setFieldsOpen]=useState(false);
  const scroll=useRef<ScrollView>(null);
  function go(n:number){setPhotoStep(n);scroll.current?.scrollTo({y:0,animated:false});}
  // Heavy OCR assets are required only when the photo flow is opened.
  const [html,setHTML]=useState('');
  useEffect(()=>{let mounted=true;void import('../generated/photo-engine').then(module=>{if(mounted)setHTML(module.PHOTO_HTML);});return ()=>{mounted=false;};},[]);
  const web=useRef<WebView>(null),ready=useRef(false),pending=useRef<string|undefined>(undefined),revision=useRef(0),epochRef=useRef(0);
  const operation=useRef<AbortController|undefined>(undefined),previewRef=useRef<RequestPreview|undefined>(undefined);
  const [epoch,setEpoch]=useState(0),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [phase,setPhase]=useState('Choose a clear, upright document photo'),[progress,setProgress]=useState<number>(),[covers,setCovers]=useState(0);
  const [result,setResult]=useState<Result>(),[confirmed,setConfirmed]=useState(false),[editing,setEditing]=useState(false),[editText,setEditText]=useState('');
  const [term,setTerm]=useState<typeof GLOSSARY[number]>(),[termsOpen,setTermsOpen]=useState(false),[textOpen,setTextOpen]=useState(false);
  const [preview,setPreview]=useState<RequestPreview>(),[approved,setApproved]=useState(false),[requestOpen,setRequestOpen]=useState(false);
  const [summary,setSummary]=useState<{summary:ReviewSummary;model:string;latencyMs:number;source:'ollama';requestHash:string}>();
  const kind=result?detectPhoto(result.lines):undefined;
  const fields=kind&&result?photoFields(kind,result.lines):[];
  const context=kind&&result?photoContext(kind,result.lines,result.masks.length,confirmed):undefined;
  const glossary=result?termsIn(result.lines.map(l=>l.text).join('\n')):[];
  const invalidate=useCallback(()=>{revision.current++;operation.current?.abort();operation.current=undefined;const p=previewRef.current;previewRef.current=undefined;if(p&&pairing)void companion(pairing,{action:'cancel',id:p.id}).catch(()=>{});setPreview(undefined);setApproved(false);setSummary(undefined);setRequestOpen(false);},[pairing,setPreview,setApproved,setSummary,setRequestOpen]);
  const clear=useCallback(()=>{invalidate();ready.current=false;pending.current=undefined;epochRef.current++;setEpoch(epochRef.current);setResult(undefined);setConfirmed(false);setLoaded(false);setBusy(false);setError('');setCovers(0);setPhase('Choose a clear, upright document photo');setProgress(undefined);setEditText('');setEditing(false);setTerm(undefined);setTermsOpen(false);setTextOpen(false);setPhotoStep(0);setCanvasOpen(false);setFieldsOpen(false);},[invalidate,setEpoch,setResult,setConfirmed,setLoaded,setBusy,setError,setCovers,setPhase,setProgress,setEditText,setEditing,setTerm,setTermsOpen,setTextOpen,setPhotoStep,setCanvasOpen,setFieldsOpen]);
  useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state==='background')clear();});return ()=>{sub.remove();operation.current?.abort();const p=previewRef.current;if(p&&pairing)void companion(pairing,{action:'cancel',id:p.id}).catch(()=>{});pending.current=undefined;};},[pairing,clear]);
  useEffect(()=>{if(!busy||result)return;const timer=setTimeout(()=>{clear();setError('Photo recognition timed out. Use a clearer page or the PDF flow.');},PHOTO_LIMITS.timeout);return ()=>clearTimeout(timer);},[busy,result,clear]);
  useEffect(()=>{web.current?.injectJavaScript(`window.photo?.setTheme?.(${dark});true;`);},[dark]);
  function flush(){if(ready.current&&pending.current){const data=pending.current;pending.current=undefined;web.current?.injectJavaScript(`window.photo.load(${JSON.stringify(data)}).catch(()=>window.ReactNativeWebView.postMessage(JSON.stringify({type:'error',message:'This photo could not be loaded. Use a JPEG or PNG under 8 MiB.'})));true;`);}}
  function load(data:string){clear();pending.current=data;setPhase('Opening your photo on this phone');}
  async function pick(camera:boolean){
    const rev=revision.current;
    try{
      if(camera){const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted)throw new Error('Allow camera access to take a document photo, or choose a photo instead.');}
      const options:ImagePicker.ImagePickerOptions={mediaTypes:['images'],base64:true,quality:0.85,allowsEditing:false,exif:false};
      const picked=camera?await ImagePicker.launchCameraAsync(options):await ImagePicker.launchImageLibraryAsync(options);
      if(picked.canceled)return;
      try{const asset=picked.assets[0];if(asset.width*asset.height>PHOTO_LIMITS.pixels||(asset.fileSize??0)>PHOTO_LIMITS.bytes||!asset.base64||asset.base64.length>PHOTO_LIMITS.bytes*1.4)throw new Error('Choose a JPEG or PNG under 8 MiB and 20 megapixels.');
        if(rev!==revision.current)return;load('data:image/jpeg;base64,'+asset.base64);
      }finally{for(const asset of picked.assets){const file=new File(asset.uri);if(asset.uri.startsWith(Paths.cache.uri)&&file.exists)file.delete();}}
    }catch(e){setError((e as Error).message);}
  }
  async function makePreview(){if(!context||!pairing)return;invalidate();const rev=revision.current,controller=new AbortController();operation.current=controller;setBusy(true);setPhase('Preparing the exact minimized AI request');setError('');
    try{const p=await verifyPreview(await companion(pairing,{action:'preview',context},controller.signal));if(rev===revision.current){previewRef.current=p;setPreview(p);setPhase('Request ready for your approval');}else void companion(pairing,{action:'discard',id:p.id}).catch(()=>{});
    }catch(e){if(rev===revision.current)setError((e as Error).message);}finally{if(rev===revision.current)setBusy(false);}}
  async function send(){if(!preview||!approved||!pairing||!context)return;const rev=revision.current,controller=new AbortController();operation.current=controller;setBusy(true);setPhase('Qwen is explaining the approved field statuses on your Mac');setError('');
    try{const value=await companion<{summary:ReviewSummary;model:string;latencyMs:number;source:'ollama';requestHash:string}>(pairing,{action:'send',id:preview.id,hash:preview.hash},controller.signal);if(value.source!=='ollama'||value.requestHash!==preview.hash)throw new Error('AI receipt did not match your approved request.');const validated=validateSummary(value.summary,context);if(rev===revision.current){setSummary({...value,summary:validated});setPhase('Real model response validated');}
    }catch(e){if(rev===revision.current)setError((e as Error).message);}finally{if(rev===revision.current){setBusy(false);setApproved(false);setPreview(undefined);previewRef.current=undefined;}}}
  function saveText(){if(!result)return;const lines=editText.split('\n').map(text=>text.trim()).filter(Boolean);if(lines.length!==result.lines.length||lines.some(t=>t.length>1000)){setError('Edit existing lines without adding or removing lines. Keep each under 1,000 characters.');return;}invalidate();setResult({...result,lines:result.lines.map((line,i)=>({...line,text:lines[i]}))});setConfirmed(false);setEditing(false);setEditText('');}
  return <SafeAreaView edges={['top']} style={s.safe}><View style={s.header}><Action title="Back" secondary onPress={()=>{clear();onClose();}}/><Text style={s.brand}>Photo review</Text><Action title="New photo" secondary onPress={clear}/></View>
    <ScrollView ref={scroll} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
      {photoStep===0&&<><Text style={s.title}>Read what you choose.</Text><Text style={s.body}>Cover private details. We’ll read only the visible picture.</Text>
      <View style={s.row}><Action title="Take a photo" testID="photo-camera" disabled={busy} onPress={()=>void pick(true)}/><Action title="Choose a photo" testID="photo-import" secondary disabled={busy} onPress={()=>void pick(false)}/></View>
      {!loaded&&!busy&&<Action title="Try synthetic statement photo" secondary testID="photo-demo" onPress={()=>{void import('../generated/photo-demo').then(module=>load(module.PHOTO_DEMO));}}/>}
      </>}<View style={s.pipeline}>{['Cover','Review','Explain'].map((label,i)=><Pressable key={label} accessibilityRole="button" accessibilityLabel={`Photo step ${i+1}: ${label}`} disabled={busy||i>0&&!result||i===2&&!confirmed} onPress={()=>go(i)} style={[s.stepButton,photoStep===i&&s.stepActive]}><Text style={[s.step,photoStep===i&&s.active]}>{i+1}  {label}</Text></Pressable>)}</View>
      <View accessibilityRole="summary" accessibilityLiveRegion="polite" style={s.status}>{busy&&<ActivityIndicator color={colors.accent}/>}<Text style={s.body}>{phase}{busy&&progress!==undefined&&!result?` · ${Math.round(progress*100)}% of this step`:''}</Text></View>
      {!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
      {result&&photoStep===1&&<Action title={canvasOpen?'Hide covered photo':'See covered photo & highlights'} secondary onPress={()=>setCanvasOpen(!canvasOpen)}/>}
      <View accessibilityElementsHidden={!(loaded&&(photoStep===0||canvasOpen&&photoStep===1))} style={[s.canvas,!(loaded&&(photoStep===0||canvasOpen&&photoStep===1))&&s.hiddenCanvas]}>{!!html&&<WebView key={epoch} ref={web} source={{html}} originWhitelist={['about:blank']} incognito allowFileAccess={false} allowUniversalAccessFromFileURLs={false} javaScriptEnabled setSupportMultipleWindows={false} scrollEnabled={true}
        onShouldStartLoadWithRequest={r=>r.url==='about:blank'} onError={()=>{clear();setError('The local photo reader closed. Choose your photo again.');}} onContentProcessDidTerminate={()=>{clear();setError('The local photo reader ran out of memory. Use a smaller photo.');}}
        onMessage={e=>{if(epoch!==epochRef.current)return;try{const v=JSON.parse(e.nativeEvent.data);if(v.type==='ready'){ready.current=true;web.current?.injectJavaScript(`window.photo?.setTheme?.(${dark});true;`);flush();}else if(v.type==='loaded'){setLoaded(true);setPhase('Cover private details, then tap Analyze visible photo');}else if(v.type==='covers'){setCovers(z.number().int().min(0).max(PHOTO_LIMITS.masks).parse(v.count));}else if(v.type==='progress'){setBusy(true);setPhase(z.string().max(150).parse(v.label));setProgress(v.progress===undefined?undefined:z.number().min(0).max(1).parse(v.progress));}else if(v.type==='result'){const data=resultSchema.parse(v);setResult({...data,lines:visibleLines(data.lines,data.masks)});setBusy(false);setProgress(undefined);setPhase('Visible text ready. Check it before asking AI.');go(1);}else if(v.type==='term'){setTerm(GLOSSARY.find(t=>t.id===v.id));}else if(v.type==='error'){setBusy(false);setError(z.string().max(300).parse(v.message));}}catch{clear();setError('The photo reader returned an invalid result. Nothing was sent to AI.');}}}/>}</View>
      {loaded&&!result&&<Text style={s.small}>{covers} cover stroke(s). Nothing is sent to a server while covering or reading the photo. Cancel ends the reader.</Text>}
      {busy&&<Action title="Cancel" secondary onPress={()=>{if(result){invalidate();setBusy(false);setPhase('AI operation cancelled. Your local review remains.');}else clear();}}/>}
      {result&&photoStep===1&&<>
        <View style={s.card}><Text style={s.heading}>What was read</Text><Text style={s.body}>{kind?`${kind==='bank-statement-v1'?'Bank statement':'Client intake'} · ${fields.filter(f=>f.status==='read').length} of ${fields.length} selected fields read.`:'This document does not match a supported photo workflow.'}</Text><Text style={s.small}>English printed text • {result.lines.length} visible lines • phone-local OCR in {(result.latencyMs/1000).toFixed(1)} s. OCR can make mistakes.</Text>
        {kind?<><Text style={s.body}>{fields.some(f=>f.status==='unread')?'Some fields were not read. They may be covered, absent or unclear; this does not establish an error in the original document.':'The selected labels have readable values. Check the source before relying on them.'}</Text><Action title={fieldsOpen?'Hide recognized fields':'Review recognized fields'} secondary onPress={()=>setFieldsOpen(!fieldsOpen)}/>{fieldsOpen&&fields.map(f=><View key={f.field} style={s.field}><Text style={s.label}>{f.label}</Text><Text selectable style={s.body}>{f.value||'Not read · covered, absent or unclear'}</Text></View>)}</>:<Text style={s.body}>You can inspect the visible text and glossary. AI review supports the selected bank statement and intake label layouts. Drawings, SSI and legal forms do not get a fabricated document review.</Text>}
        <Text style={s.small}>Covered lines are excluded. The original photo is no longer available in this editor. This does not delete the original from your Photos library.</Text>
        <Action title={textOpen?'Hide visible text':'Inspect visible text'} secondary onPress={()=>setTextOpen(!textOpen)}/>{textOpen&&result.lines.map((l,i)=><Text key={i} selectable style={s.quote}>{l.text}</Text>)}
        <Action title="Correct visible text" secondary disabled={busy} onPress={()=>{setEditText(result.lines.map(l=>l.text).join('\n'));setEditing(true);}}/>
        <Action title={confirmed?'Visible text confirmed':'I checked the visible text'} disabled={busy||confirmed||!kind} onPress={()=>{invalidate();setConfirmed(true);}}/>
        </View>
        <View style={s.card}><Text style={s.heading}>Understand the terms</Text><Text style={s.body}>Tap Show terms above to highlight recognized words, or select a term here. Definitions are a local glossary, not AI output.</Text><Action title={termsOpen?'Hide term list':'Show term list'} secondary onPress={()=>setTermsOpen(!termsOpen)}/>{termsOpen&&<View style={s.row}>{glossary.length?glossary.map(g=><Action key={g.id} title={g.term} testID={`term-${g.id}`} secondary onPress={()=>setTerm(g)}/>):<Text style={s.small}>No glossary terms were recognized in the visible text.</Text>}</View>}</View>
      </>}
      {result&&photoStep===2&&<>
        {kind&&<View style={s.card}><Text style={s.heading}>Decide what AI receives</Text><Text style={s.body}>The photo stays here. Qwen gets field read/unread states and your confirmation, after you approve the request.</Text><Text style={s.small}>No names, account numbers, amounts, dates or pixels. AI explains the review status.</Text>
          {!pairing?<Text style={s.body}>Open Settings and pair your Mac to use real AI. The local photo review works without it.</Text>:<Action title="Preview photo AI request" disabled={busy||!confirmed} onPress={()=>void makePreview()}/>}
          {preview&&<><Action title="View exact photo request" secondary onPress={()=>setRequestOpen(true)}/><Pressable accessibilityRole="checkbox" accessibilityLabel="Approve photo minimized request" accessibilityState={{checked:approved}} disabled={busy} onPress={()=>setApproved(!approved)} style={s.approve}><Text style={s.body}>{approved?'☑':'☐'} I approve these exact minimized facts being sent to Qwen on my Mac.</Text></Pressable><Action title="Explain approved photo review" disabled={!approved||busy} onPress={()=>void send()}/></>}
        </View>}
        {summary&&<View style={s.card}><Text style={s.heading}>AI explanation · real Qwen</Text><Text style={s.body}>{summary.summary.overview}</Text>{summary.summary.findings.map(f=><View key={f.id} style={s.field}><Text style={s.label}>{f.id==='photo_fields'?'Visible field review':'Text confirmation'}</Text><Text style={s.body}>{f.explanation}</Text><Text style={s.small}>{f.follow_up}</Text></View>)}<Text style={s.small}>{summary.model} · {(summary.latencyMs/1000).toFixed(1)} s · validated on receipt</Text><Text selectable style={s.code}>{summary.requestHash}</Text></View>}
      </>}

    </ScrollView>
    {result&&photoStep===1&&<View style={s.footer}><Action title="Continue to photo AI" disabled={!confirmed||!kind||busy} onPress={()=>go(2)}/></View>}
    <Modal visible={!!term} animationType="slide" onRequestClose={()=>setTerm(undefined)}><SafeAreaProvider><SafeAreaView style={s.safe}><View style={s.content}><Text style={s.title}>{term?.term}</Text><Text style={s.body}>{term?.definition}</Text>{term&&'source' in term&&<Text selectable style={s.small}>Source: {term.source}</Text>}<Text style={s.small}>General glossary explanation; no interpretation of your legal rights or benefit eligibility.</Text><Action title="Close definition" onPress={()=>setTerm(undefined)}/></View></SafeAreaView></SafeAreaProvider></Modal>
    <Modal visible={editing} animationType="slide" onRequestClose={()=>{setEditing(false);setEditText('');}}><SafeAreaProvider><SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.heading}>Correct visible OCR text</Text><Text style={s.body}>Edit existing lines only. Do not re-enter covered private details. Corrections clear the previous AI approval and result.</Text><TextInput accessibilityLabel="Visible photo text" multiline value={editText} onChangeText={setEditText} style={s.input}/><Action title="Save photo corrections" onPress={saveText}/><Action title="Cancel correction" secondary onPress={()=>{setEditing(false);setEditText('');}}/></ScrollView></SafeAreaView></SafeAreaProvider></Modal>
    <Modal visible={requestOpen&&!!preview} animationType="slide" onRequestClose={()=>setRequestOpen(false)}><SafeAreaProvider><SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Action title="Close photo request" onPress={()=>setRequestOpen(false)}/><Text style={s.heading}>Exactly what Qwen receives</Text><Text style={s.small}>Destination on your Mac: {preview?.destination}. Approval expires after five minutes and can be used once.</Text><Text selectable style={s.code}>{preview?.hash}{"\n\n"}{preview?.serializedBody}</Text></ScrollView></SafeAreaView></SafeAreaProvider></Modal>
  </SafeAreaView>;
}
const makeStyles=(c:Palette)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.background},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:12,borderBottomWidth:1,borderColor:c.border},brand:{fontSize:17,fontWeight:'600',color:c.text},content:{padding:24,gap:20,paddingBottom:32},title:{fontSize:29,lineHeight:35,fontWeight:'600',color:c.text},heading:{fontSize:20,fontWeight:'600',color:c.text},body:{fontSize:15,lineHeight:23,color:c.text},small:{fontSize:12,lineHeight:19,color:c.muted},row:{flexDirection:'row',flexWrap:'wrap',gap:8},button:{minHeight:48,backgroundColor:c.accent,borderRadius:12,padding:14,alignItems:'center'},buttonText:{fontSize:14,fontWeight:'600',color:c.onAccent},secondary:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border},secondaryText:{color:c.text},disabled:{opacity:.45},card:{backgroundColor:c.card,borderRadius:20,padding:18,gap:14,borderWidth:1,borderColor:c.border},canvas:{height:620,borderRadius:16,overflow:'hidden',backgroundColor:c.card},hiddenCanvas:{height:1,opacity:0},pipeline:{flexDirection:'row',gap:4},stepButton:{flex:1,minHeight:42,alignItems:'center',justifyContent:'center',borderBottomWidth:2,borderBottomColor:c.border},stepActive:{borderBottomColor:c.accent},step:{fontSize:12,color:c.muted},active:{color:c.accent,fontWeight:'600'},status:{flexDirection:'row',gap:10,alignItems:'center',padding:12,backgroundColor:c.surface,borderRadius:12},error:{color:c.error,backgroundColor:c.soft,padding:14,borderRadius:12,fontSize:14,lineHeight:21},field:{paddingVertical:10,borderBottomWidth:1,borderColor:c.border,gap:4},label:{fontSize:14,fontWeight:'600',color:c.text},quote:{fontSize:13,lineHeight:21,color:c.text,backgroundColor:c.surface,padding:10},code:{fontFamily:'Menlo',fontSize:10,lineHeight:16,color:c.text,backgroundColor:c.surface,padding:10},input:{minHeight:350,borderWidth:1,borderColor:c.border,borderRadius:12,padding:14,color:c.text,backgroundColor:c.surface,textAlignVertical:'top'},approve:{padding:14,borderWidth:1,borderColor:c.border,borderRadius:12},footer:{padding:16,borderTopWidth:1,borderColor:c.border}});
