import React from 'react';
import { Pressable, Text, View, StyleSheet, type TextStyle, type StyleProp, type ColorValue } from 'react-native';
import Svg, { Path, Circle, Rect } from 'react-native-svg';
import { translateDisplay } from '../../src/shared/locales';
import { useAppearance } from '../lib/appearance';

export type IconName='home'|'document'|'settings'|'globe'|'camera'|'arrow'|'back'|'shield'|'sun'|'moon'|'check'|'close'|'link';
const paths:Record<IconName,string>={home:'M3 10l9-7 9 7v10H3V10m6 10v-7h6v7',document:'M6 3h8l4 4v14H6V3m8 0v5h4M9 12h6m-6 4h6',settings:'M4 7h16M4 17h16',globe:'M2 12h20M12 2c-6 5-6 15 0 20 6-5 6-15 0-20',camera:'M3 7h4l2-3h6l2 3h4v13H3V7',arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3m-4 9 3 3 5-6',sun:'M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2',moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11',check:'M5 12l4 4L19 6',close:'M6 6l12 12M6 18 18 6',link:'M10 14l4-4m-5 6-2 2a4 4 0 0 1-6-6l4-4m10 0 2-2a4 4 0 0 1 6 6l-4 4'};
export function Icon({name,size=24,color}:{name:IconName;size?:number;color?:ColorValue}){const {colors}=useAppearance();return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color??colors.text} strokeWidth={1.7} strokeLinecap="round" strokeLinejoin="round"><Path d={paths[name]}/>{name==='globe'&&<Circle cx="12" cy="12" r="10"/>}{name==='camera'&&<Circle cx="12" cy="13" r="4"/>}{name==='sun'&&<Circle cx="12" cy="12" r="5"/>}{name==='settings'&&<><Rect x="8" y="4" width="4" height="6" rx="2" fill={colors.background}/><Rect x="14" y="14" width="4" height="6" rx="2" fill={colors.background}/></>}</Svg>;}
export function Copy({children,size=15,bold=false,muted=false,style}:{children:string;size?:number;bold?:boolean;muted?:boolean;style?:StyleProp<TextStyle>}){const {colors,locale}=useAppearance();return <Text style={[{fontSize:size,lineHeight:size*1.4,fontWeight:bold?'600':'400',color:muted?colors.muted:colors.text},style]}>{translateDisplay(children,locale)}</Text>;}
export function ActionButton({title,onPress,secondary=false,disabled=false,icon,testID}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;icon?:IconName;testID?:string}){const {colors,locale}=useAppearance();return <Pressable accessibilityRole="button" accessibilityState={{disabled}} testID={testID} disabled={disabled} onPress={onPress} style={[styles.button,{backgroundColor:secondary?colors.surface:colors.accent,borderColor:secondary?colors.border:colors.accent,opacity:disabled?.45:1}]}>{icon&&<Icon name={icon} size={20} color={secondary?colors.text:colors.onAccent}/>}<Text style={{fontSize:15,fontWeight:'600',color:secondary?colors.text:colors.onAccent}}>{translateDisplay(title,locale)}</Text></Pressable>;}
export function PageHeader({title,onBack,right}:{title:string;onBack?:()=>void;right?:React.ReactNode}){const {colors}=useAppearance();return <View style={[styles.header,{borderColor:colors.border}]}>{onBack?<Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={onBack} style={styles.iconButton}><Icon name="back"/></Pressable>:<View style={{width:44}}/>}<Copy bold size={17}>{title}</Copy><View style={{minWidth:44,alignItems:'flex-end'}}>{right}</View></View>;}
export const styles=StyleSheet.create({page:{padding:24,gap:24,paddingBottom:32},button:{minHeight:50,borderWidth:1,borderRadius:12,paddingVertical:13,paddingHorizontal:18,flexDirection:'row',gap:10,justifyContent:'center',alignItems:'center'},header:{minHeight:62,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1},iconButton:{width:44,height:44,alignItems:'center',justifyContent:'center'},row:{flexDirection:'row',alignItems:'center',gap:12}});
