import React from 'react';
import {Pressable,ScrollView,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import {LOCALES} from '../../src/shared/locales';
import {useAppearance} from '../lib/appearance';
import {COUNTRIES} from '../lib/countries';
import {ActionButton,Copy,Icon,PageHeader,styles} from '../components/UI';
import PairMac from '../components/PairMac';
export default function SettingsScreen(){const {colors,mode,setMode,locale,setLocale,country}=useAppearance();return <SafeAreaView edges={['top']} style={{flex:1,backgroundColor:colors.background}}><PageHeader title="Settings"/><ScrollView contentContainerStyle={styles.page}><View style={{gap:16}}><Copy size={24} bold>Your preferences</Copy><Copy bold>Appearance</Copy><View style={{flexDirection:'row',gap:8}}>{(['light','dark','system'] as const).map(id=><Pressable key={id} testID={`theme-${id}`} accessibilityRole="button" accessibilityLabel={`${id} mode`} accessibilityState={{selected:mode===id}} onPress={()=>setMode(id)} style={{flex:1,alignItems:'center',gap:8,paddingVertical:16,borderRadius:12,borderWidth:1,borderColor:mode===id?colors.accent:colors.border,backgroundColor:mode===id?colors.soft:colors.surface}}><Icon name={id==='dark'?'moon':id==='light'?'sun':'settings'} color={mode===id?colors.accent:colors.text}/><Copy size={13}>{id==='system'?'System':id==='light'?'Light':'Dark'}</Copy></Pressable>)}</View></View><View style={{gap:12,borderTopWidth:1,borderColor:colors.border,paddingTop:24}}><Copy bold>Country & language</Copy><ActionButton title={COUNTRIES.find(c=>c.id===country)!.name} secondary icon="globe" onPress={()=>router.push('/countries')}/>{LOCALES.map(([id,label])=><Pressable key={id} testID={`locale-${id}`} accessibilityRole="button" accessibilityLabel={`Language ${label}`} accessibilityState={{selected:locale===id}} onPress={()=>setLocale(id)} style={{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:colors.border}}><Copy>{label}</Copy>{locale===id&&<Icon name="check" color={colors.accent}/>}</Pressable>)}<Copy muted size={12}>Display language only. Original documents and exact AI requests stay unchanged. Photo OCR reads English.</Copy></View><View style={{borderTopWidth:1,borderColor:colors.border,paddingTop:24}}><PairMac/></View><View style={{gap:12,borderTopWidth:1,borderColor:colors.border,paddingTop:24}}><Copy bold>Private by design</Copy><Copy muted size={13}>Documents stay in memory on your phone. Backgrounding clears the workspace and connection. Original files stay in Files or Photos.</Copy><Copy muted size={13}>Supported: sample intake and bank statement, selected typed DE/EN Schengen PDF, and selected English bank/intake photos.</Copy></View></ScrollView></SafeAreaView>;}
